name: CIs
on:
  pull_request:
    branches:
      - main

jobs:
  flake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8
      - name: Lint with flake8
        run: flake8

  pytest:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu, windows, macos ]
        python: [ '3.10' ]
        name: [ matrix ]
    name: pytest ${{ matrix.os }} / ${{matrix.python}}
    runs-on: ${{ matrix.os }}-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: |  # use MNE main to ensure test files are available
          python -m pip install -ve . -r requirements.txt -r requirements_dev.txt
      - uses: actions/cache@v2
        with:
          key: sample-data
          path: ~/mne_data/MNE-sample-data
        name: 'Cache testing data'
      - run: python -c 'import mne; print(mne.datasets.testing.data_path(verbose=True))'
        name: 'Download sample data'
      - name: Show system information
        run: mne sys_info
      - run: pytest
        name: Run Tests